config/routes.rb
Rails.application.routes.draw do
  get "signin" => "sessions#new"
  resource :session
  get "signup" => "candidates#new", as: "signup"
  resources :candidates

  get "register" => "employers#new", as: "register"
  resources :employers 
    

  root "jobs#index"
  get "jobs/post" => "jobs#new"
  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :employer

	validates :title, :experience, :employment_type, :location, 
   :job_link, presence: true
  validates :description, length: { minimum: 25 }

  INDUSTRY = ['Accounting', 'Airlines/Aviation', "Alternative Disputs Resolution", "Alternative Medicine", "Animation", "Apparel & Fashion", 
    "Architecture & Planning", "Arts & Crafts", "Automotive", "Banking", "Biotechnology", "Broadcast Media", "Building Materials", "Capital Markets", "Commercial Real Estate",
   "Computer Software", "Computer hardware & Network Security", "Construction", 'Consumer Electronics', 'Consumer Services', "Dairy", "Education Management", "E-Learning", "Entertainment", "Information Technology and Services",
   "Hospital & Health Care", "Import and Export", "Internet", "Government", "Legal", "Management Consulting", "Marketing and Advertising", "Military", "Nonprofit Organization Management",
   "Oil & Energy","Professional Training & Coaching", "Restaurants", "Research", "Security and Investigations", "Sports", "Staffing and Recruiting", "Transportation", "Venture Capital & Private Equity", "Other"]
  #validates :sex, inclusion: { in: SEX }

  EXPERIENCE = ['Internship', 'Entry-level', 'Mid-level', 'Senior-level', "Associate", "Executive", "Director", "CEO", "Not Applicable"]
  EMPLOYMENT_TYPE = ['Full Time', 'Part Time', 'Contract', 'Contract', "Contract to Hire", "Temporary", "Other"]
  EXPERIENCE = ['Internship', 'Entry-level', 'Mid-level', 'Senior-level', "Associate", "Executive", "Director", "CEO", "Not Applicable"]
  SALARY_RATE = ['Hourly', 'Weekly', 'Monthly', 'Annually']
  RELOCATION = ['NO', '0 - 20%', '20 - 40%', '40 - 60%', '60 - 80%', "80 - 100%"]
  TRAVEL = ["NO", '0 - 20%', '20 - 40%', '40 - 60%', '60 - 80%', "80 - 100%"]
  COMPANY_SIZE = ["1 - 10 Employees", "11 - 50 Employees", "51 - 100 Employees", "101 - 200 Employees", "201 - 500 Employees", "501 - 1000 Employees", "1001 - 5000 Employees", "5000+ Employees"]

  def self.recent
    order("created_at desc")
  end
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :require_signin, except: [:index, :show]
	#before_action :correct_employer_job, only: [:edit, :update]
	#before_action :correct_employer, only: [:edit, :update]
	before_action :require_admin, only: [:destroy]

	def index
		@jobs = Job.recent
	end

	def show
		@job = Job.find(params[:id])
	end

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		if @job.update(job_params)
			flash[:notice]='Job updated successfully'
		  redirect_to @job
		else
			render :edit
		end
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(job_params)
		if @job.save
		 redirect_to @job, notice: "Job successfully created!"
		else
			render :new
		end
	end

	def destroy
		@job = Job.find(params[:id])
		@job.destroy
		redirect_to jobs_url, alert: "Job has been deleted"
	end

	private

	def job_params
		params.require(:job).permit(:title,:company,:description,
							:skill,:location,:industry,:company_size,:website,:key_responsibility,
							:state,:zip_code,:country,:salary,:salary_rate,:employment_type,:experience,
							:relocation,:travel,:other_pay,:job_link,:company_description
		 )
	end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class='container'>
<div class='row'>
<br>
<div class='col-md-9'>
<%= form_for @job, :html => { :multipart => true } do |f| %>
<%= render "shared/errors", object: @job %>
<div class='form-horizontal' role='form'>
  <div class="form-group">
  <div class='row'>
  <div class='col-md-3'>
    <%= f.label :company, class: 'control-label' %></div>
    <div class='col-md-7'>
    <%= f.text_field :company, autofocus: true, placeholder: "Company Name", class: "form-control" %>
  </div></div><br>
  <div class='row'>
  <div class='col-md-3'>
    <%= f.label :industry, class: 'control-label' %></div>
    <div class='col-md-7'>
    <%= f.select :industry, Job::INDUSTRY, prompt: "Select one", class: "form-control" %>

  </div></div>
  <div class='row'>
  <div class='col-md-3'>
    <%= f.label :company_size, class: 'control-label' %></div>
    <div class='col-md-7'>
    <%= f.select :company_size, Job::COMPANY_SIZE, prompt: "Select one", class: "form-control" %></div></div><br>
 <div class='row'>
  <div class='col-md-3'>
    <%= f.label :company_description, class: 'control-label' %></div>
    <div class='col-md-7'>
    <%= f.text_area :company_description, cols: 40, rows: 7, autofocus: true, placeholder: "Brief description about your company, what you are up to, service and product", class: "form-control" %>
  </div></div><br>
  <div class='row'>
  <div class='col-md-3'>
    <%= f.label :website, "Company Website", class: 'control-label' %></div>
    <div class='col-md-7'>
    <%= f.text_field :website, autofocus: true, placeholder: "http://companyname.com", class: "form-control" %>
  </div></div><br>

   <div class='row'>
  <div class='col-md-3'>
    <%= f.label :title, "Job Title", class: 'control-label' %></div>
    <div class='col-md-7'>
    <%= f.text_field :title, autofocus: true, placeholder: "Job title", class: "form-control" %>
  </div></div><br>
   <div class='row'>
  <div class='col-md-3'>
    <%= f.label :description, class: 'control-label' %></div>
    <div class='col-md-7'>
    <%= f.text_area :description, cols: 40, rows: 7, autofocus: true, placeholder: "Job description", class: "form-control" %>
  </div></div><br>
  <div class='row'>
  <div class='col-md-3'>
    <%= f.label :skill, class: 'control-label' %></div>
    <div class='col-md-7'>
    <%= f.text_area :skill, cols: 40, rows: 7, class: "form-control" %>
  </div></div><br>
  <div class='row'>
  <div class='col-md-3'>
    <%= f.label :key_responsibility, class: 'control-label' %></div>
    <div class='col-md-7'>
    <%= f.text_area :key_responsibility, cols: 40, rows: 7, placeholder: "List of job responsibilties",class: "form-control" %>
  </div></div><br>
  <div class='row'>
  <div class='col-md-3'>
    <%= f.label :location, class: 'control-label' %></div>
    <div class='col-md-7'>
    <div class='col-md-6'>
    <%= f.text_field :location, class: "form-control", cols: 20, placeholder: "Austin" %><br>
     <%= f.text_field :zip_code, class: "form-control", placeholder: "78701" %></div>
    <div class='col-md-6'>
      <%= f.text_field :state, class: "form-control", placeholder: "Texas" %><br>
      <%= f.text_field :country, class: "form-control", placeholder: "USA" %>
    </div>
  </div></div><br>
  
  <div class='row'>
  <div class='col-md-3'>
    <%= f.label :salary, class: 'control-label' %></div>
    <div class='col-md-7'>
    <div class='col-md-8'>
    <%= f.text_field :salary, class: "form-control" %></div>
    <div class='col-md-4'>
    <%= f.select :salary_rate, Job::SALARY_RATE, prompt: "Select one", class: "form-control" %></div>
  </div></div><br>
  
  <div class='row'>
  <div class='col-md-3'>
    <%= f.label :employment_type, class: 'control-label' %></div>
    <div class='col-md-7'>
    <div class='col-md-4'>
    <%= f.select :employment_type, Job::EMPLOYMENT_TYPE, prompt: "Select one", class: "form-control" %></div>
    <div class='col-md-8'>
    <div class='col-md-7'>
    <%= f.label :experience, class: 'control-label' %></div>
    <div class='col-md-5'>
    <%= f.select :experience, Job::EXPERIENCE, prompt: "Select one", class: "form-control" %>

  </div></div>
    </div></div><br>

  <div class='row'>
  <div class='col-md-3'>
    <%= f.label :relocation, class: 'control-label' %></div>
    <div class='col-md-7'>
    <div class='col-md-4'>
    <%= f.select :relocation, Job::RELOCATION, prompt: "Select one", class: "form-control" %></div>
    <div class='col-md-8'>
    <div class='col-md-7'>
    <%= f.label :travel, class: 'control-label' %></div>
    <div class='col-md-5'>
    <%= f.select :travel, Job::TRAVEL, prompt: "Select one", class: "form-control" %>

  </div></div>
    </div></div><br>

    <div class='row'>
  <div class='col-md-3'>
    <%= f.label :other_pay, class: 'control-label' %></div>
    <div class='col-md-7'>
    <%= f.text_field :other_pay, class: "form-control" %>
  </div></div><br>

  <div class='row'>
  <div class='col-md-3'>
    <%= f.label :job_link, class: 'control-label' %></div>
    <div class='col-md-7'>
    <%= f.text_field :job_link, class: "form-control", placeholder: "http://companyname.com/job.html" %>
  </div></div><br>
<br>

  </div></div>
  <div class='row'>
  <div class='col-md-3'></div>
  <div class='col-md-8'>
    <%= f.submit class: 'btn btn-success' %> <%= link_to "Cancel", jobs_path, class: 'btn btn-warning' %>
  </div></div>
</div></div>
<% end %>
</div>
<div class='col-md-2 ico'>
<br><br>
</div>
</div>
</div>
</div>

app/views/jobs/edit.html.erb
<h1><%= @job.title %></h1>

<%= render "form" %>

app/views/jobs/index.html.erb
<h1><%= pluralize(@jobs.size, "Job") %></h1>


<% @jobs.each do |job| %>
<article>
<header>
<h2><%= job.company %> - <%= link_to(job.title, job_url(job)) %></h2>
</header>
<p><%= truncate(job.description, length: 40, seperator: " ") %></p>
<table>
<tr>
<th>Skill:</th>
<td><%= job.skill %></td>
</tr>
<tr>
<th>Location:</th>
<td><%= job.location %></td>
</tr>
</table>
</article>
<% end %>

app/views/jobs/new.html.erb
<h2>Post a Job</h2>
<%= render 'form' %>

app/views/jobs/show.html.erb
<article>
<header>
<h2><%= @job.company %> - <%= @job.title %></h2>
</header>
<p><%= @job.description %></p>
<table>
<tr>
<th>Skill:</th>
<td><%= @job.skill %></td>
</tr>
<tr>
<th>Location:</th>
<td><%= @job.location %></td>
</tr>
</table>
</article>

<%# if current_employer?(@employer) %>
<%= link_to "Edit", edit_job_path(@job) %> 
<%# end %>
<% if current_candidate_admin? || current_employer_admin? %>
| <%= link_to 'Delete', job_path(@job), method: :delete, data: {confirm: "Are You Sure?"} %>
<% end %>