config/routes.rb
Rails.application.routes.draw do
  get "signin" => "sessions#new"
  resource :session
  get "signup" => "candidates#new", as: "signup"
  resources :candidates

  get "register" => "employers#new", as: "register"
  resources :employers 
    

  root "jobs#index"
  get "jobs/post" => "jobs#new"
  resources :jobs

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_secure_password

  validates :password, length: { minimum: 8, allow_blank: true }

  validates :name, presence: true
  validates :email, presence: true,
                  format: /\A\S+@\S+\z/,
                  uniqueness: { case_sensitive: false }

  validates :username, presence: true,
                     format: /\A[A-Z0-9]+\z/i,
                     uniqueness: { case_sensitive: false }
 
   def self.authenticate(email_or_username,password)
  	candidate = Candidate.find_by(email:email_or_username) || Candidate.find_by(username: email_or_username)
  	candidate && candidate.authenticate(password)
  end
      
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
	before_action :require_signin, except: [:new, :create]
	before_action :require_correct_candidate, only: [:edit, :update]
	before_action :require_admin, only: [:destroy]

	def index
		@candidates = Candidate.all 
	end

	def show
		@candidate = Candidate.find(params[:id])
	end

	def new
		@candidate = Candidate.new
	end

	def create
		@candidate = Candidate.new(candidate_params)
		if @candidate.save
			session[:candidate_id] = @candidate.id
			redirect_to @candidate, notice: "Thanks for signing up as candidate"
		else
			render :new
		end
	end

	def edit
		@candidate = Candidate.find(params[:id])
	end

	def update
		@candidate = Candidate.find(params[:id])
		if @candidate.update(candidate_params)
			redirect_to @candidate
		else
			render :edit
		end
	end

	def destroy
		@candidate = Candidate.find(params[:id])
		@candidate.destroy
		#session[:candidate_id] = nil
		redirect_to root_path, alert: "Account has been deleted, sorry to see you going!"
	end


	private

	def require_correct_candidate
		@candidate = Candidate.find(params[:id])
			redirect_to root_url unless current_candidate?(@candidate)
		end

	def candidate_params
		params.require(:candidate).permit(:name,:email,:password,:password_confirmation,:username,:about, :accomplish, :powerpoint, :specialization, :location, :sex, :phone, :school, :work, :marital, :video, :github, :twitter, :linkedin, :dribbble, :facebook, :degree, :start_year, :grad_year)
	end

end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <%= render "shared/errors", object: @candidate %>
  <fieldset>

      <p class="required">


        <%= f.text_field :name, size: 50, autofocus: true, placeholder: "Full name" %>
      </p>
      <p class="required">

          <%= f.text_field :username, size: 50,
                    placeholder: "Username Alphanumeric characters only!" %>
</p>
      <p class="required">

        <%= f.email_field :email, size: 50, placeholder: "Email Address" %>
      </p>
      <p class="required">

        <%= f.password_field :password, size: 50, placeholder: "Password 8 or more characters" %></p>

      <p class="required">
        <%= f.password_field :password_confirmation, size: 50, placeholder: "Confirm Password" %></p>

    <p>
      <% if @candidate.new_record? %>
        <%= f.submit "Create Account" %>
      <% else %>
        <%= f.submit "Update Account" %>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/candidates/edit.html.erb
<div class='container'>
  <div class='row'>
  <br><br>
   <h2>Update Your Profile</h2><br>
     <%= render 'form' %>
</div>
</div>

app/views/candidates/index.html.erb
<div class='container'>
<div class='row'>
<div class='row'>

<% if @candidates.any? %>
<% @candidates.in_groups_of(4) do |group| %>
<div class='row'>
<% group.each do |candidate| %>
<% if candidate %>
<div class='col-md-3'>
<div class='row'>
<div class='col-md-4'>
     <p><%#= profile_image_for(candidate) %></p></div>
  <div class='col-md-8'>
      <h4><%= link_to candidate.name, candidate %></h4>
      <h5><%= candidate.email %></h5>
      <h5><%= candidate.location %></h5>
      </div>
</div><br>
</div>
<% end %>
<% end %>
</div>
<% end %>
<% end %>


</div>
</div>

app/views/candidates/new.html.erb
<div class='container'>
<div class='row'>
<br>
<%= render 'form' %>

</div>
</div>

app/views/candidates/show.html.erb
<div class='container'>
  <div class='row user_main'>
<br><br>
  <h2><%= @candidate.name %></h2>
  <h4><%= @candidate.email %></h4>
</div>
</div>

<% if current_candidate?(@candidate) %>
<%= link_to "Edit", edit_candidate_path(@candidate) %> | 
<% end %>
<% if current_candidate_admin? %>
<%= link_to 'Delete Account', candidate_path(@candidate), method: :delete, data: {confirm: "Are You Sure?"} %>
<% end %>