config/routes.rb
Rails.application.routes.draw do
  get "signin" => "sessions#new"
  resource :session
  get "signup" => "candidates#new", as: "signup"
  resources :candidates

  get "register" => "employers#new", as: "register"
  resources :employers 
    

  root "jobs#index"
  get "jobs/post" => "jobs#new"
  resources :jobs

end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :jobs, dependent: :destroy

	has_secure_password

	validates :password, length: { minimum: 8, allow_blank: true }

  validates :name, presence: true
  validates :email, presence: true,
                  format: /\A\S+@\S+\z/,
                  uniqueness: { case_sensitive: false }

  validates :username, presence: true,
                     format: /\A[A-Z0-9]+\z/i,
                     uniqueness: { case_sensitive: false }
       

  def self.authenticate(email_or_username,password)
  	employer = Employer.find_by(email:email_or_username) || Employer.find_by(username: email_or_username)
  	employer && employer.authenticate(password)
  end

end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
	before_action :require_signin, except: [:new, :create]
	before_action :require_correct_employer, only: [:edit, :update]
	before_action :require_admin, only: [:destroy]

	def index
		@employers = Employer.all 
	end

	def show
		@employer = Employer.find(params[:id])
	end

	def new
		@employer = Employer.new
	end

	def edit
		@employer = Employer.find(params[:id])
	end

	def update
		@employer = Employer.find(params[:id])
		if @employer.update(employer_params)
			redirect_to @employer
		else
			render :edit
		end
	end

	def create
		@employer = Employer.new(employer_params)
		if @employer.save
			session[:employer_id] = @employer.index
			redirect_to @employer, notice: "Thanks for signing up as employer!"
		else
			render :new
		end
	end

	def destroy
		@employer = Employer.find(params[:id])
		@employer.destroy
		#session[:employer_id] = nil
		redirect_to root_path, alert: "Account has been deleted, sorry to see you going!"
	end

	private

	def require_correct_employer
		@employer = Employer.find(params[:id])
		 #unless current_employer== @employer
			redirect_to root_url unless current_employer?(@employer)
	end

	helper_method :require_correct_employer

	def employer_params
		params.require(:employer).permit(:name, :email, :password, :password_confirmation, :username,:about,:state,:city,
			:zipcode,:country,:twitter,:linkedin,:facebook,:website, :company_name, :heard_us)
	end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= form_for(@employer) do |f| %>
  <%= render "shared/errors", object: @employer %>
  <fieldset>

      <p class="required">


        <%= f.text_field :name, size: 50, autofocus: true, placeholder: "Full name" %>
      </p>
      <p class="required">

          <%= f.text_field :username, size: 50,
                    placeholder: "Username Alphanumeric characters only!" %>
</p>
       <p class="required">

          <%= f.text_field :company_name, size: 50,
                    placeholder: "Company Name!" %>
</p>
      <p class="required">

        <%= f.email_field :email, size: 50, placeholder: "Email Address" %>
      </p>
      <p class="required">

        <%= f.password_field :password, size: 50, placeholder: "Password 8 or more characters" %></p>

      <p class="required">
        <%= f.password_field :password_confirmation, size: 50, placeholder: "Confirm Password" %></p>

    <p>
      <% if @employer.new_record? %>
        <%= f.submit "Create Account" %>
      <% else %>
        <%= f.submit "Update Account" %>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/employers/index.html.erb
<div class='container'>
<div class='row'>
<div class='row'>

<% if @employers.any? %>
<% @employers.in_groups_of(4) do |group| %>
<div class='row'>
<% group.each do |employer| %>
<% if employer %>
<div class='col-md-3'>
<div class='row'>
<div class='col-md-4'>
     <p><%#= profile_image_for(employer) %></p></div>
  <div class='col-md-8'>
      <h4><%= link_to employer.name, employer %></h4>
      <h5><%= employer.email %></h5>
      <h5><%= employer.company_name %></h5>
      <h5><%= employer.state %></h5>
      </div>
</div><br>
</div>
<% end %>
<% end %>
</div>
<% end %>
<% end %>


</div>
</div>

app/views/employers/show.html.erb
<div class='container'>
  <div class='row user_main'>
<br><br>
  <h2><%= @employer.name %></h2>
  <h4><%= @employer.email %></h4>
</div>
</div>
<% if current_employer?(@employer) %>
<%= link_to "Edit", edit_employer_path(@employer) %> 
<% end %>
|
<% if current_employer_admin? %> 
<%= link_to 'Delete Account', employer_path(@employer), method: :delete, data: {confirm: "Are You Sure?"} %>
<% end %>