config/routes.rb
Rails.application.routes.draw do
  get "signin" => "sessions#new"
  resource :session
  get "signup" => "candidates#new", as: "signup"
  resources :candidates

  get "register" => "employers#new", as: "register"
  resources :employers 
    

  root "jobs#index"
  get "jobs/post" => "jobs#new"
  resources :jobs

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <%= link_to 'All Jobs', jobs_path, class: 'navbar-brand' %>
      <%= link_to 'Post a Job', jobs_post_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if current_candidate %>
<li><%= link_to "Employers", register_path %></li>
<li><%= link_to current_candidate.name, current_candidate %></li>
<li><%= link_to "Account Setting", edit_candidate_path(current_candidate) %></li>
<li><%= link_to 'Sign Out', session_path, method: :delete %></li>
<% elsif current_employer %>
<li><%= link_to "Candidates", signup_path %></li>
<li><%= link_to current_employer.name, current_employer %></li>
<li><%= link_to "Account Setting", edit_employer_path(current_employer) %></li>
<li><%= link_to 'Sign Out', session_path, method: :delete %></li>
<% else %>
<li><%= link_to "Employers", register_path %></li>
<li><%= link_to "Candidates", signup_path %></li>
<li><%= link_to "Sign In", signin_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Jobs" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Jobs" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>